title: My Portfolio
description: This is my portfolio site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mohamedasli.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-include-cache
remote_theme: mmistakes/minimal-mistakes@4.26.2

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true